[tool.poetry]
name = "dbt-northwind"
version = "0.1.0"
description = ""
authors = ["silmara-basso"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"
dbt-postgres = "^1.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
